### ISSUE TITLE
"Status: Disabled; game was likely running when KI-O first started or you loaded a savestate with KI-O disabled."

### ISSUE THREAD

**Issue by vanillaDSi** [projectcomet64/metal-orchestrator#7]
I've been having a few problems trying to use MOrk with chroma-key savestates. I click "_Ensemble_", start the ROM, enter a save file in said ROM, and try to load a savestate. But whenever I do this, as soon as the savestate loads, it says the following:
_"Status: Disabled; game was likely running when KI-O first started or you loaded a savestate with KI-O disabled."_
I can't figure out what causes this, since I had KI-O running when I loaded the savestate. Could you explain this to me so I'll know how to avoid it in the future?

**Comment by GlitchyPSIX** [comment]
If you load a savestate without the KI-O code written, you will find this error. This is because KI-O writes some indicators in memory to find out whether the code has been written and it's ready to use. Using a savestate somebody else made without KI-O code will effectively erase the code from memory.

(This may not be required with Engine 2, but it will be a while before Engine 2 is ready. #8 )
